YCloudYUSA/yusaopeny_gated_content

modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/config/install/openy_gc_auth.provider.reclique_sso.yml, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Controller/SSOController.php, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Form/TryAgainForm.php, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Plugin/GCIdentityProvider/RecliqueSSO.php
**Related Issue/Ticket:** YMCA Dallas client work - improving error handling on ReClique SSO. ReClique doesn't have specific error messages but I took guidance from https://github.com/YCloudYUSA/yusaopeny_gated_content/blob/15dd85f4f93b61f3235a78951176f42fb0e0bbbc/modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/config/install/openy_gc_auth.provider.daxko_barcode.yml#L5-L9
team in Slack
=> Improve error handling for ReClique SSO

assets/css/admin_ui_styles.css
Tiny fix to icon path. Will probably need to be fixed again if things move.
team in Slack
=> bug: Update icon path from profile to module

modules/openy_gc_auth/modules/openy_gc_auth_example/js/openy_gc_auth_example.js, modules/openy_gc_auth/modules/openy_gc_auth_example/openy_gc_auth_example.libraries.yml, modules/openy_gc_auth/modules/openy_gc_auth_example/src/Form/VirtualYExampleLoginForm.php, modules/openy_gc_auth/modules/openy_gc_auth_example/src/Plugin/GCIdentityProvider/Example.php
Add option for dummy provider to "auto-login", providing a kind of "demo mode" for VY
team in Slack
=> feat: Add autologin option to Dummy provider

modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/config/install/openy_gc_auth.provider.reclique_sso.yml, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.services.yml, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Controller/SSOController.php, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/EventSubscriber/GCAuthReCliqueSSOUserLoginSubscriber.php, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Plugin/GCIdentityProvider/RecliqueSSO.php, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/SSOClient.php
Adds permissions mapping to gc_auth_reclique_sso. This change attempts to keep the existing behavior the same but add a number of options to increase flexibility for different ReClique setups. It also cleans up some changes from #2.
The ReClique SSO configuration now has a number of additional fields, all of which default to their prior behavior but provide options for flexible permissions mapping.
team in Slack
=> feat: Add permissions mapping to reclique_sso

modules/openy_gc_log/config/install/openy_gc_log.settings.yml, modules/openy_gc_log/openy_gc_log.module, modules/openy_gc_log/src/Form/LogSettingsForm.php, modules/openy_gc_log/src/LogArchiver.php
**YUOPENY-8**
**PLEASE CHECK BASE BRANCH FOR YOUR PR**
**ONLY urgent and approved fixes for point release should go to master branch**
https://fivejars.atlassian.net/browse/YUOPENY-8
team in Slack
=> Add on|off toggle for log_archiver cron job in config 

assets/css/openy_lily.css
**Related Issue/Ticket:** YUOPENY-19
[https://fivejars.atlassian.net/browse/YUOPENY-19](https://fivejars.atlassian.net/browse/YUOPENY-19)
- [x ] No updates are necessary for this change.
- [x ] Tested against Lily
team in Slack
=> [Lily theme]Remove empty space between the menu and the date bar [YUOPENY-19]

modules/openy_gc_shared_content/src/Controller/PreviewController.php
**[Shared Content] Preview doesn't work**
[(DS-47)](https://yusa.atlassian.net/browse/DS-47)
team in Slack
=> [Shared Content] Preview doesn't work [DS-47]

composer.json, modules/openy_gc_log/src/Field/PayloadFieldItemList.php
as per https://www.drupal.org/project/payment/issues/2878691#comment-12088007
this also requires https://www.drupal.org/project/video/issues/3332771
https://yusa.atlassian.net/browse/DS-16
https://github.com/fivejars/openy_gated_content/pull/418
The reproduction steps from https://github.com/fivejars/openy_gated_content/pull/418
don't seem to work any more, even with all of these changes reverted, but once merged all functionality of Virtual Y, Virtual Y Logs, and Virtual Y Search should function as before with no errors.
team in Slack
=> DS-16 Remove patches and fix PayloadFieldItemList

modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
**Related Issue/Ticket:** [#20 ](https://github.com/YCloudYUSA/yusaopeny_gated_content/issues/20)
In this PR was added a new checkbox and submit button was to update the Daxko whitelist redirect URL. Now to update this whitelist needs to do an extra effort.
team in Slack
=> [DS-275] Add a separate submit's handler to update the Daxko Whitelist URL

modules/openy_gc_autologout/js/openy_gc_autologout.js, modules/openy_gc_autologout/openy_gc_autologout.libraries.yml
[DS-218](https://yusa.atlassian.net/browse/DS-218)
team in Slack
=> [DS-218] autologout: Don't log out if user is playing a video #17

modules/openy_gc_storage/openy_gc_storage.install
Fixes #7 
https://yusa.atlassian.net/browse/DS-68
This isn't really testable as it applies to an old update hook. Only way would be to roll back to an old version, reproduce the issue (that was hard to reproduce) and then run updates.
team in Slack
=> DS-68 Clean up gc_duration field before config import.

assets/css/y_lb.css, config/install/core.entity_view_display.block_content.virtual_y_app.default.yml, config/install/core.entity_view_display.block_content.virtual_y_login.default.yml, config/install/field.storage.block_content.field_virtual_y_login.yml, openy_gated_content.install, openy_gated_content.libraries.yml, openy_gated_content.module, templates/block--virtual-y-app.html.twig
- [DS-778](https://yusa.atlassian.net/browse/DS-778)
- [DS-780](https://yusa.atlassian.net/browse/DS-780)
- [DS-781](https://yusa.atlassian.net/browse/DS-781)
- [DS-779](https://yusa.atlassian.net/browse/DS-779)
team in Slack
=> [DS-778] Fix the Virtual Y Content and Virtual Y Login blocks for the Layout Builder

assets/css/y_lb.css, openy_gated_content.libraries.yml, openy_gated_content.module
[DS-794](https://yusa.atlassian.net/browse/DS-794)
Desktop:
Tablet:
Mobile:
team in Slack
=> [DS-794] Fix styles of the Virtual Y content page for LB for the Carnation theme

modules/openy_gc_auth/src/GCAuthManager.php
[DS-795](https://yusa.atlassian.net/browse/DS-795)
team in Slack
=> [DS-795] Fix redirect after login for Virtual Y App in LB

openy_gated_content.install
Resolves update issues like:
>  [error]  Configuration <em class="placeholder">editor.editor.full_html</em> depends on the <em class="placeholder">CKEditor 5</em> module that will not be installed after import. 
and
>  [error]  Column information not available for the 'event_instances' field. 
Also ensure https://www.drupal.org/project/recurring_events/issues/3376639 is committed or added via patch if not.
**Related Issue/Ticket:** 
**PLEASE CHECK BASE BRANCH FOR YOUR PR**
**ONLY urgent and approved fixes for point release should go to master branch**
https://yusa.atlassian.net/browse/DS-902
see also https://github.com/YCloudYUSA/yusaopeny/pull/94
- …
=> fix: Add update dependencies for ckeditor5 and recurring_events

assets/css/y_lb.css, openy_gated_content.libraries.yml
[DS-875](https://yusa.atlassian.net/browse/DS-875?focusedCommentId=12804)
team in Slack
=> [DS-875] Add a small fix for the Virtual Y header after QA phase

modules/openy_gc_log/openy_gc_log.module, modules/openy_gc_log/openy_gc_log.post_update.php, modules/openy_gc_log/src/LogArchiver.php, modules/openy_gc_log/src/Logger.php
[DS-903](https://yusa.atlassian.net/browse/DS-903)
Should fix these errors:
team in Slack
=> [DS-1157] Add accessCheck for DB queries

assets/css/openy_carnation.css, openy_gated_content.libraries.yml
Community request
team in Slack
=> Revert main nav font size change

modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/Plugin/GCIdentityProvider/AvocadoSSO.php
I have faced the issue on a site that uses Avocado virtual Y logic and as I can see this happens because of the function sendWelcomeEmail(). the AvocadoSSO trying to send an email but since it has no openy_gated_content.user_service added to its construct we have a fatal error.
=> Add missing openy_gated_content.user_service to Avocado SSO provider

assets/css/y_lb.css, openy_gated_content.libraries.yml
[DS-1076](https://yusa.atlassian.net/browse/DS-1076)
team in Slack
=> [DS-1076] Fix heading position for pages without alerts banner

modules/openy_gc_storage/config/install/recurring_events.eventseries.config.yml, modules/openy_gc_storage/openy_gc_storage.install
[DS-1204](https://yusa.atlassian.net/browse/DS-1204)
team in Slack
=> [DS-1204] Set default value for creator_plugin options of the eventseries config

modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_live_stream.yml, modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_virtual_meeting.yml
[DS-805](https://yusa.atlassian.net/browse/DS-805)
team in Slack
=> [DS-805] Fix the end time of the demo events to display the correct duration information in the schedule.

modules/openy_gc_auth/js/auth.behaviors.js, modules/openy_gc_auth/modules/openy_gc_auth_example/js/openy_gc_auth_example.js, modules/openy_gc_auth/modules/openy_gc_auth_example/openy_gc_auth_example.libraries.yml, modules/openy_gc_auth/openy_gc_auth.libraries.yml
[DS-1300](https://yusa.atlassian.net/browse/DS-1300)
team in Slack
=> [Ds-1300] Fix deprecation code (once and cookie) in js files

modules/openy_gc_auth/modules/openy_gc_auth_example/js/openy_gc_auth_example.js
[DS-1300](https://yusa.atlassian.net/browse/DS-1300)
team in Slack
=> [DS-1300] Add a fix for the auto-submit auth form functionality of the openy_gc_auth_example module

js/gated-content/package.json, openy_gated_content.libraries.yml
[DS-889](https://yusa.atlassian.net/browse/DS-889)
team in Slack
=> [DS-889] Upgrade axios library up to version 1.4

modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
Just add null-safe operator to avoid $request is undefined error after try/catch block.
=> fix: 500(white page) error when daxko return error response
